name: Deploy Function

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      PROJECT_ID: ${{ secrets.PROJECT_ID }}

    steps:
      - uses: actions/checkout@v3

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Deploy Functions
        run: supabase functions deploy --project-ref $PROJECT_ID
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          BASE_URL: ${{ secrets.BASE_URL }}
          USER_AGENT: ${{ secrets.USER_AGENT }}
          DECRYPT_ALGO: ${{ secrets.DECRYPT_ALGO }}
          PASS_KEY_ALG: ${{ secrets.PASS_KEY_ALG }}
          PASS_KEY_SUB: ${{ secrets.PASS_KEY_SUB }}
          PASS_ZIP_ALG: ${{ secrets.PASS_ZIP_ALG }}
          PASS_ZIP_SUB: ${{ secrets.PASS_ZIP_SUB }}
          PASS_PDF_ALG: ${{ secrets.PASS_PDF_ALG }}
          PASS_PDF_SUB: ${{ secrets.PASS_PDF_SUB }}